# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eic-vocab' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eic-vocab
  pod 'React', path: '../node_modules/react-native', subspecs: ['ART']
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  target 'eic-vocab-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eic-vocabTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
